### ISSUE TITLE
Update Modularity section

### ISSUE THREAD

**Issue by decebals** [decebals/pippo-site#25]
The `Initializer` implementation was simplificated in last version. No need for `pippo.properties` file.
Now we use the Service Loader mechanism from Java (`META-INF/services`).
From version 0.9.0 you can use a simple annotation (see https://github.com/decebals/pippo/pull/243).

**Comment by gitblit** [comment]
> From version 0.9.0 you can use a simple annotation (see decebals/pippo#243).

This implies that the user can just use that annotation - but they need to manually add that dependency; it's a `provided` dependency in Pippo.  We could change that if you think it adds value.

**Comment by decebals** [comment]
It's better to not be forced to manually add that dependency in my Pippo module but I don't know how we can do this. The perfect location to declare this dependency is `pippo-core` but I don't want to have this dependency at runtime and I don't know if it's possible to specify that I need that dependency only for compile operation (an `compiler` scope or something like this). I am not a Maven expert. Maybe someone can help us.
