### ISSUE TITLE
Add more info about available session implementations

### ISSUE THREAD

**Issue by decebals** [decebals/pippo-site#31]
Hazelcast, Ehcache, ... 

http://www.pippo.ro/doc/session.html

**Comment by decebals** [comment]
@barrantesgerman Can you help me with this issue, please?

**Comment by barrantesgerman** [comment]
Sorry for answer until today
I will try to do it this weekend

**Comment by decebals** [comment]
No problem

**Comment by decebals** [comment]
Thanks!
